version: '3.4'
services:
    mariadb:
        image: mariadb:10.5
        command: --transaction-isolation=READ-COMMITTED
        container_name: olt-database
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        environment:
            TZ: "Europe/Bucharest"
            MYSQL_RANDOM_ROOT_PASSWORD: 'Yes'
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
        volumes:
            - /var/lib/mysql_olt:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        networks:
            - olt-network
            - public

    olt-ftp:
        image: fauria/vsftpd
        container_name: olt-ftp
        stop_signal: SIGINT
        environment:
            TZ: "Europe/Bucharest"
            FTP_USER:
            FTP_PASS:
            PASV_ENABLE: "YES" 
            PASV_MIN_PORT: "11320" 
            PASV_MAX_PORT: "11350" 
            REVERSE_LOOKUP_ENABLE: "NO" 
            LOG_STDOUT: "yes" 
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        ports:
            - "21:21"
            - "20:20"
            - "11320-11350:11320-11350"
        volumes:
            - /home/olt-ftp:/home/vsftpd
            - /var/log/vsftpd:/var/log/vsftpd
            - /etc/localtime:/etc/localtime:ro

        restart: unless-stopped
        networks:
            - olt-network
            - public

    redis-server:
        image: redis:6.0.8-alpine
        container_name: olt-redis-server
        restart: unless-stopped
        environment:
            TZ: "Europe/Bucharest"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - olt-network

    olt:
        depends_on:
            - mariadb
            - redis-server
        image: $CI_REGISTRY_IMAGE:latest
        #build:
        #  context: .
        #image: olt-app
        container_name: olt-app
        restart: unless-stopped
        dns:
            - 188.173.1.2
            - 188.173.1.3
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        environment:
            TZ: "Europe/Bucharest"
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_HOST:
            SECRET_KEY:
            REDIS_URL:
            ENV_TYPE:
            OLT_DOMAIN:
            AUTHORIZED_ACCOUNTS:
            DEBUG:
            VERBOSE:
            QUIET:
            DEBUG_SQL:
            DEBUG_TELNET:
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/log/olt:/opt/OLT/logs
            - /etc/letsencrypt:/etc/letsencrypt
            - /home/olt-ftp:/opt/OLT/ftp
        ports:
            - "6001:6001"
        networks:
            - olt-network
            - public

    redis-worker:
        depends_on:
            - redis-server
            - olt
        image: $CI_REGISTRY_IMAGE:latest
        #build:
        #  context: .
        #image: olt-redis-worker
        entrypoint: python /opt/OLT/manage.py run_worker
        container_name: olt-redis-worker
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        environment:
            TZ: "Europe/Bucharest"
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_HOST:
            SECRET_KEY:
            ENV_TYPE:
            REDIS_URL:
            OLT_DOMAIN:
            AUTHORIZED_ACCOUNTS:
            DEBUG:
            VERBOSE:
            QUIET:
            DEBUG_SQL:
            DEBUG_TELNET:
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - olt-network
            - public

networks:
  olt-network:
    internal: true
  public:
