"""Adding quantity to products

Revision ID: 30a1e7af2ebe
Revises: 62192a359fa5
Create Date: 2021-02-20 19:53:44.689884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a1e7af2ebe'
down_revision = '62192a359fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cantity')
    # ### end Alembic commands ###
