"""Adding quantity to products2

Revision ID: 6c86c6ea7000
Revises: 30a1e7af2ebe
Create Date: 2021-02-20 19:54:44.273684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c86c6ea7000'
down_revision = '30a1e7af2ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('products', 'cantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
