"""changing nullable

Revision ID: 6e1a6c12a276
Revises: 75c131d85410
Create Date: 2021-02-24 20:46:50.699858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e1a6c12a276'
down_revision = '75c131d85410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
